// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"sync"
	"time"

	"github.com/hecomp/session-management/internal/models"
	"github.com/hecomp/session-management/pkg/repository"
)

type FakeSessionMgmntRepository struct {
	CreateStub        func(string, time.Time) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 string
		arg2 time.Time
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	DestroyStub        func(*models.DestroyRequest) error
	destroyMutex       sync.RWMutex
	destroyArgsForCall []struct {
		arg1 *models.DestroyRequest
	}
	destroyReturns struct {
		result1 error
	}
	destroyReturnsOnCall map[int]struct {
		result1 error
	}
	ExistStub        func(string) (bool, error)
	existMutex       sync.RWMutex
	existArgsForCall []struct {
		arg1 string
	}
	existReturns struct {
		result1 bool
		result2 error
	}
	existReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	ExtendStub        func(*models.ExtendRequest) error
	extendMutex       sync.RWMutex
	extendArgsForCall []struct {
		arg1 *models.ExtendRequest
	}
	extendReturns struct {
		result1 error
	}
	extendReturnsOnCall map[int]struct {
		result1 error
	}
	ListStub        func() (*models.Sessions, error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
	}
	listReturns struct {
		result1 *models.Sessions
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 *models.Sessions
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSessionMgmntRepository) Create(arg1 string, arg2 time.Time) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 string
		arg2 time.Time
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSessionMgmntRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeSessionMgmntRepository) CreateCalls(stub func(string, time.Time) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeSessionMgmntRepository) CreateArgsForCall(i int) (string, time.Time) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSessionMgmntRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionMgmntRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionMgmntRepository) Destroy(arg1 *models.DestroyRequest) error {
	fake.destroyMutex.Lock()
	ret, specificReturn := fake.destroyReturnsOnCall[len(fake.destroyArgsForCall)]
	fake.destroyArgsForCall = append(fake.destroyArgsForCall, struct {
		arg1 *models.DestroyRequest
	}{arg1})
	stub := fake.DestroyStub
	fakeReturns := fake.destroyReturns
	fake.recordInvocation("Destroy", []interface{}{arg1})
	fake.destroyMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSessionMgmntRepository) DestroyCallCount() int {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return len(fake.destroyArgsForCall)
}

func (fake *FakeSessionMgmntRepository) DestroyCalls(stub func(*models.DestroyRequest) error) {
	fake.destroyMutex.Lock()
	defer fake.destroyMutex.Unlock()
	fake.DestroyStub = stub
}

func (fake *FakeSessionMgmntRepository) DestroyArgsForCall(i int) *models.DestroyRequest {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	argsForCall := fake.destroyArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSessionMgmntRepository) DestroyReturns(result1 error) {
	fake.destroyMutex.Lock()
	defer fake.destroyMutex.Unlock()
	fake.DestroyStub = nil
	fake.destroyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionMgmntRepository) DestroyReturnsOnCall(i int, result1 error) {
	fake.destroyMutex.Lock()
	defer fake.destroyMutex.Unlock()
	fake.DestroyStub = nil
	if fake.destroyReturnsOnCall == nil {
		fake.destroyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.destroyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionMgmntRepository) Exist(arg1 string) (bool, error) {
	fake.existMutex.Lock()
	ret, specificReturn := fake.existReturnsOnCall[len(fake.existArgsForCall)]
	fake.existArgsForCall = append(fake.existArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ExistStub
	fakeReturns := fake.existReturns
	fake.recordInvocation("Exist", []interface{}{arg1})
	fake.existMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionMgmntRepository) ExistCallCount() int {
	fake.existMutex.RLock()
	defer fake.existMutex.RUnlock()
	return len(fake.existArgsForCall)
}

func (fake *FakeSessionMgmntRepository) ExistCalls(stub func(string) (bool, error)) {
	fake.existMutex.Lock()
	defer fake.existMutex.Unlock()
	fake.ExistStub = stub
}

func (fake *FakeSessionMgmntRepository) ExistArgsForCall(i int) string {
	fake.existMutex.RLock()
	defer fake.existMutex.RUnlock()
	argsForCall := fake.existArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSessionMgmntRepository) ExistReturns(result1 bool, result2 error) {
	fake.existMutex.Lock()
	defer fake.existMutex.Unlock()
	fake.ExistStub = nil
	fake.existReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionMgmntRepository) ExistReturnsOnCall(i int, result1 bool, result2 error) {
	fake.existMutex.Lock()
	defer fake.existMutex.Unlock()
	fake.ExistStub = nil
	if fake.existReturnsOnCall == nil {
		fake.existReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.existReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionMgmntRepository) Extend(arg1 *models.ExtendRequest) error {
	fake.extendMutex.Lock()
	ret, specificReturn := fake.extendReturnsOnCall[len(fake.extendArgsForCall)]
	fake.extendArgsForCall = append(fake.extendArgsForCall, struct {
		arg1 *models.ExtendRequest
	}{arg1})
	stub := fake.ExtendStub
	fakeReturns := fake.extendReturns
	fake.recordInvocation("Extend", []interface{}{arg1})
	fake.extendMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSessionMgmntRepository) ExtendCallCount() int {
	fake.extendMutex.RLock()
	defer fake.extendMutex.RUnlock()
	return len(fake.extendArgsForCall)
}

func (fake *FakeSessionMgmntRepository) ExtendCalls(stub func(*models.ExtendRequest) error) {
	fake.extendMutex.Lock()
	defer fake.extendMutex.Unlock()
	fake.ExtendStub = stub
}

func (fake *FakeSessionMgmntRepository) ExtendArgsForCall(i int) *models.ExtendRequest {
	fake.extendMutex.RLock()
	defer fake.extendMutex.RUnlock()
	argsForCall := fake.extendArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSessionMgmntRepository) ExtendReturns(result1 error) {
	fake.extendMutex.Lock()
	defer fake.extendMutex.Unlock()
	fake.ExtendStub = nil
	fake.extendReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionMgmntRepository) ExtendReturnsOnCall(i int, result1 error) {
	fake.extendMutex.Lock()
	defer fake.extendMutex.Unlock()
	fake.ExtendStub = nil
	if fake.extendReturnsOnCall == nil {
		fake.extendReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.extendReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSessionMgmntRepository) List() (*models.Sessions, error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
	}{})
	stub := fake.ListStub
	fakeReturns := fake.listReturns
	fake.recordInvocation("List", []interface{}{})
	fake.listMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSessionMgmntRepository) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeSessionMgmntRepository) ListCalls(stub func() (*models.Sessions, error)) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = stub
}

func (fake *FakeSessionMgmntRepository) ListReturns(result1 *models.Sessions, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 *models.Sessions
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionMgmntRepository) ListReturnsOnCall(i int, result1 *models.Sessions, result2 error) {
	fake.listMutex.Lock()
	defer fake.listMutex.Unlock()
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 *models.Sessions
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 *models.Sessions
		result2 error
	}{result1, result2}
}

func (fake *FakeSessionMgmntRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	fake.existMutex.RLock()
	defer fake.existMutex.RUnlock()
	fake.extendMutex.RLock()
	defer fake.extendMutex.RUnlock()
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSessionMgmntRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.SessionMgmntRepository = new(FakeSessionMgmntRepository)
